const esbuild = require('esbuild');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
esbuild.buildSync({ entryPoints: [path.join(__dirname, 'xz.js')], bundle: true, write: false,
    format: 'iife', globalName: 'SeaSubsXZ', target: 'es2018', minify: true,
    inject: [path.join(__dirname, 'buffer-inject.js')],
    alias: { 'extract-base-iterator': path.join(__dirname, 'buffer-shim.js'),
        'xz-compat/dist/esm/lzma/sync/Lzma2Decoder.js': path.join(path.dirname(require.resolve('xz-compat/package.json')), 'dist/esm/lzma/sync/Lzma2Decoder.js') }
}).outputFiles.forEach(f => fs.writeFileSync(path.join(root, 'code.ts'),
    '// Generated by npm run build. Edit source.ts and scripts/, then rebuild.\n// @ts-nocheck\n' +
    '// XZ decoder: xz-compat 1.2.10 (MIT); buffer 6.0.3 (MIT). See THIRD_PARTY_NOTICES.md.\n' +
    fs.readFileSync(path.join(root, 'source.ts'), 'utf8').replace('$ui.register((ctx) => {', '$ui.register((ctx) => {\n' + f.text + '\n')));
